#!/bin/sh

# This can be used in a comment as a reminder to self.
git diff-index --cached -S "DONOTCOMMIT" HEAD --patch --exit-code ":!githooks" \
    || { echo; echo "Have you forgotten about the “DONOTCOMMIT”?"; exit 1; }

# Eldev functions can be used during development, but must not be committed.
git diff-index --cached -S "eldev-" HEAD --patch --exit-code ":!githooks" ":!Eldev" \
    || { echo; echo "Don't commit code relying on Eldev!"; exit 1; }
